print ('')
print (' ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨')
print ('Cálculo de média de notas')
print ('----------------------------')
print ('Solicitando entrada de dados')
print ('----------------------------')
aluno = str (input ('informe o nome do aluno')) 
n1=float (input ('Informe a 1º nota: '))
n2=float (input ('Informe o 2º nota: '))
n3=float (input ('informe o 3º nota: '))
n4=float (input ('informe o 4º nota: '))
print ('')
print ('|------------------------------|')
print ('|       EFETUANDO O CÁLCULO    |')
print ('|------------------------------|')
r=(n1+n2+n3+n4)/ 4
print ('')
print ('a média do aluno',aluno,'é: ',r)
print (r)
print ('')
print (' * FIM DO CÁLCULO * ')
print ('')


