print ('')
print (' ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨')
print ('Cálculo de Circunferência')
print ('----------------------------')
print ('Solicitando entrada de dados')
print ('----------------------------')
r=float (input ('Informe o valor do raio: '))
print ('')
print ('|------------------------------|')
print ('| CALCULANDO ÁREA DA CIRCUNFERÊNCIA |')
print ('|------------------------------|')
c=2*3,14*r
print ('')
print ('O resultado da circunferência é: ',c)
print ('')
print (' *** FIM DO CÁLCULO *** ')
print ('')

