print ('')
print (' ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨')
print ('Soma de 2 valores')
print ('----------------------------')
print ('Solicitando entrada de dados')
print ('----------------------------')
num1=float (input ('Informe o 1º valor: '))
num2=float (input ('Informe o 2º valor: '))
print ('')
print ('|------------------------------|')
print ('| SOMANDO OS VALORES INSERIDOS |')
print ('|------------------------------|')
r=num1+num2
print ('')
print ('O resultado da soma é: ',r)
print ('')
print (' *** FIM DO CÁLCULO *** ')
print ('')