print ('')
print (' Cálculo de Idade')
print (' ¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨')
print ('Calcular idade de qualquer pessoa')
print ('----------------------------')
print ('Solicitando entrada de dados')
print ('----------------------------')
a_a=float (input ('Informe o ano atual: '))
a_n=float (input ('Informe o ano de nascimento: '))
print ('')
print ('|------------------------------|')
print ('|       Calculando a Idade    |')
print ('|------------------------------|')
r=a_a-a_n
print ('')
print ('A Idade é: ',r)
print ('')
print (' * FIM DO CÁLCULO * ')
print ('')
